### ISSUE TITLE
Question: Is there any way for Harvesters/Baggers to check that the upload of their file was successful?

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#20] opened 2017-02-22 22:08 UTC
_From @khdelphine on February 9, 2017 20:12_

_Copied from original issue: b5/pipeline#51_

**Comment by kmcculloch** [comment] 2017-02-26 23:24
@khdelphine Is this a duplicate of https://github.com/edgi-govdata-archiving/archivers.space/issues/42 ?

**Comment by khdelphine** [comment] 2017-02-28 12:18
@kmcculloch, no, I don't think it is a duplicate of #42.  

#42 is a bug report (the string “harvest_url” appearing instead of the actual url in certain situations).

However I think #20 can be closed, because it was opened at a time when there was no ways for harvesters to see the URL of the zip file they had just uploaded. The Archivers app was just not showing it. So the harvesters had no way to check that the upload was successful and could only "hope for the best".

**Closed as completed** 2017-02-28 23:38 UTC
Labels: question, documentation needed
